sudo: required

language: rust
rust:
  - stable

services:
  - docker

before_install:
  - docker pull mrkloan/tomorrow:latest
  - docker run --name tomorrow -v $(pwd):/src -td mrkloan/tomorrow bash
  - docker ps -a

script:
  - docker exec tomorrow bash -c "cd /src && python3 models/*.py"
  - docker exec tomorrow bash -c "cd /src && cargo test"

after_success:
  - docker stop tomorrow
  - git clone https://github.com/tomorrow-paper/ci-scripts.git
  - chmod +x ./ci-scripts/cargo_bump.sh
  - ./ci-scripts/cargo_bump.sh
 
notifications:
  email:
    on_success: never
    on_failure: always